### ISSUE TITLE
Run.bat file does not work?

### ISSUE THREAD

**Issue by MrParrot2212** [bigger0gamer/AMGEM#4]
I'm on windows 11, and just installed the latest version of Java, and when I double click the run.bat file, it shows this:
![Screenshot 2024-12-27 182835](https://github.com/user-attachments/assets/08c2f1ed-3422-4349-81cf-7d2f9fd79ea1)
I know I must be doing something wrong, but I don't know what I'm doing wrong.

**Comment by bigger0gamer** [comment]
AMGEM was built with JDK11, but you have Java 8 JRE installed. You'll need to [download JDK11 or newer](https://www.oracle.com/java/technologies/downloads/) to get AMGEM to run.

Sorry about this, but that's honestly one of the things I fucked up making this little program (and same with H2GEM). Starting with Java 9 and newer, it's supposed to be the developers job to bundle the JRE with their apps, and I just didn't know that when I wrote this. (I also should have bundled the class files together into a jar file, which I did know and didn't care to do.)

At any rate: I haven't maintained this tool in like, 4 years. Among Us has had a lot of new stuff added or changed since. I haven't really played since 2020 myself, but I know that total players has increased, there's a whole lot more maps, and who knows what else. Case in point: I just checked [the steam guide that I used to build this tool](https://steamcommunity.com/sharedfiles/filedetails/?id=2248906495), and what do you know? People in the comments have reported that the guide is completely irrelevant now, so this tool is too. If you want to do some of the cool things this tool would have allowed, then you're either gonna have to play a really old version, or make a new tool from the ground up. Sorry about that, but I don't want to you to waste your time with something that doesn't work anymore anyways.

Guess I should go update README.md that this tool is outdated and go archive this repo.
